# Generated by Django 5.1.5 on 2025-01-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
