# Generated by Django 5.1.5 on 2025-01-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_attendancelog_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='qr_code_url',
        ),
    ]
