# Generated by Django 5.1.5 on 2025-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_remove_workplace_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
