# Generated by Django 5.1.5 on 2025-02-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_user_is_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_checked_in',
        ),
    ]
