# Generated by Django 5.1.5 on 2025-02-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_alter_attendancelog_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
    ]
