# Generated by Django 5.1.5 on 2025-02-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_alter_workplace_latitude_alter_workplace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=12, null=True),
        ),
    ]
