# Generated by Django 5.1.5 on 2025-02-07 18:32

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_alter_attendancelog_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=secrets.token_urlsafe, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
